### ISSUE TITLE
Add collection of standard Nunjucks filters

### ISSUE THREAD

**Issue by paulrobertlloyd** [x-govuk/govuk-prototype-filters#1]
Provide a set of useful and commonly used filters that can be used in Nunjucks templates, grouped by type, and documented using JSDoc. Perhaps these should exist in `./lib/nunjucks/filters`, leaving `./app/filters.js` free for project-specific filters?

@edwardhorsford has already done a lot of the heavy lifting here, given all the [filters included in the Register trainee teachers prototype](https://github.com/DFE-Digital/register-trainee-teachers-prototype/blob/main/app/filters/utility.js).

Alternatively, we could [expose lodash](https://github.com/DFE-Digital/register-trainee-teachers-prototype/blob/f7c7aaf5531f15a2b2dd1e6f5cc1789015a79330/app/filters/utility.js#L19) and be done with it? 

## Candidates for initial inclusion

Will need to research names used across other projects to provide some level of predictability around the filters we include. 

### Array

* [x] `isArray` x-govuk/govuk-prototype-rig#6
* [x] `formatList` x-govuk/govuk-prototype-rig#18
* [x] ~`removeWhere`~ `rejectFromArray` x-govuk/govuk-prototype-rig#18
* [x] ~`where`~ `selectFromArray` x-govuk/govuk-prototype-rig#18 

### Date

* [x] `govukDate` x-govuk/govuk-prototype-rig#5
* [x] `govukTime` x-govuk/govuk-prototype-rig#6
* [x] `isoDateFromDateInput` x-govuk/govuk-prototype-rig#5
* [x] `month` x-govuk/govuk-prototype-filters#10

### Object

* [x] `isObject` x-govuk/govuk-prototype-rig#6
* [x] `objectToArray` x-govuk/govuk-prototype-rig#18

### Number

* [x] `isNumber` x-govuk/govuk-prototype-rig#6
* [x] `currency` x-govuk/govuk-prototype-rig#5
* [x] `ordinal` x-govuk/govuk-prototype-rig#121
* [x] `plural` x-govuk/govuk-prototype-rig#122

### String

* [x] `isString` x-govuk/govuk-prototype-rig#6
* [x] `govukMarkdown` x-govuk/govuk-prototype-rig#8
* [x] `noOrphans` x-govuk/govuk-prototype-rig#5
* [x] `slugify` x-govuk/govuk-prototype-rig#5
* [x] `startsWith` x-govuk/govuk-prototype-rig#7

## Candidates for later inclusion

Later releases could be used to provide additional filters for managing arrays and objects. That said, given the many different types of operation you might want to perform, with data modelled in untold different ways, perhaps such filters fall out of scope of this project?

### Array

* `toArray`
* `combineArrays`
* `limitTo`
* `push`
* `removeEmpty`
* `cleanArray`
* `find`

### Object

* `mergeObjects`
* `objectArrayToArray`
* `deleteAttribute`
* `deleteBlankAttributes`

**Comment by paulrobertlloyd** [comment]
Have updated this issue to split filters into 2 categories: those to consider for initial inclusion, and those to think about for later releases. Basically, cheating so that we can close this tracking issue. New filters can be tracked in individual issue thread.
